### ISSUE TITLE
Input string was not in a correct format

### ISSUE THREAD

**Issue by aborderon** [UddyOrizu/Word2Vec#1]
Hello,
I am interested in your project but I'm still new to word2vec and I would like to succeed to make it work locally but I get the following error at launch :

`Unhandled Exception: System.FormatException: Input string was not in a correct format.`

![capture du 2018-01-08 15-26-16](https://user-images.githubusercontent.com/6728728/34674997-59966ef4-f488-11e7-9d36-cdc23a27a60c.png)

I downloaded the google model (Pre-trained word and phrase vectors) available here :
https://code.google.com/archive/p/word2vec/

And download link : https://drive.google.com/file/d/0B7XkCwpI5KDYNlNUTTlSS21pQmM/edit?usp=sharing

I created a corspus.txt file at the root of my project.

Do you have any idea of ​​my problem?

**Comment by UddyOrizu** [comment]
Hi @aborderon  

The error seems to be a regular .net string fromat error have you checked the value u are trying to convert ?? 

I am not sure i understand the question are u trying to use the google Pre-trained word and phrase vectors with this code?? or are you creating your own model from a corpus ?? 

this word2vec code is to be used to create your own model for simantic relatedness 
a corpus can be  a collection of reviews from amazon or  latest down load of wikipedia  articles or news articles or medical articlies 

https://dumps.wikimedia.org/enwiki/latest/

http://jmcauley.ucsd.edu/data/amazon/

http://mlg.ucd.ie/datasets/bbc.html

as the google Word vector dimensions is 300 and this is using 75 dimensions  (code will need to be modifed to make the pre-trained vectors work on it)

in the train method 
word2vec.Train("corpus.txt", "model.bin");
specify  the full path to ur corpus and path to where u want ure model to be saved by default code will look in bin/debug for the corpus.txt and save the model.bin in the same folder(bin/debug).

**Comment by UddyOrizu** [comment]
@aborderon  i may be able to find time next weekend to add a method that creates a model from googles pretrained vectors

**Comment by aborderon** [comment]
Thank you for your answer, I wish to create my own model from a corpus but it would be interesting to be able to use a method that creates a model from googles pretrained vectors.

For my problem, I just downloaded a collection of wikipedia articles (https://dumps.wikimedia.org/enwiki/latest/), I added the XML file (enwiki-latest-abstract.xml) in my project,  the file is found but I get the same error in another place :

![capture du 2018-01-08 16-24-08](https://user-images.githubusercontent.com/6728728/34677740-54465154-f491-11e7-8ffb-332ae94169ae.png)

My train method
`word2vec.Train("enwiki-latest-abstract.xml", "model.bin");`

Thank you ;)

**Comment by UddyOrizu** [comment]
Hi @aborderon 
this should be fixed now problem with spacing in then foreach loop pls do a pull 

pls confrim so i can close the issue : )

i will a try and update the code to create model from google pre-traine vectors  this week or next

**Comment by aborderon** [comment]
Thank you for your merge request, I have no problem, you can close this issue ;)

But, the train is aging my pc and I enter to the swap (I5 Core and 4go) ...

Do you know a small corpus to perform some tests?

**Comment by UddyOrizu** [comment]
it depends on what u want to do and the corpus you train with will determine how the model behaves 

i have a model for the first 1 billion words from wiki the model is about 90mb corpus is 12GB and the amazon reviews model is about 250mb corpus is about 13GB as well i can share with you if you want ??  i can only share the model as i dont have a lot of space on my google drive :) 

alternatively u can use create one from http://mlg.ucd.ie/datasets/bbc.html download the raw files and merge all into i text file call corpus.txt and train test with that

**Comment by aborderon** [comment]
Thank you, I managed to do the tests locally.
